core:
  - core-01
  - core-02
  - core-03
  - core-04
  - core-05
  - core-06
  - core-07
  - core-08
  - core-09
  - core-10
  - core-11
  - core-12
  - core-13
  - core-14
  - core-15
  - core-16
  - core-17
  - core-18
  - core-19
  - core-20
  - core-21
  - core-22
  - core-23
  - core-24
  - core-25
  - core-26
  - core-27
  - core-28
  - core-29
  - core-30
stress:
  - stress-01
  - stress-02
  - stress-03
  - stress-04
  - stress-05
  - stress-06
  - stress-07
  - stress-08
  - stress-09
  - stress-10
  - stress-11
  - stress-12
  - stress-13
  - stress-14
  - stress-15
  - stress-16
  - stress-17
  - stress-18
  - stress-19
  - stress-20
